### ISSUE TITLE
Launch at Login - Legacy doesn't launch at login

### ISSUE THREAD

**Issue by taramk** [darwinkitdev/upwork-demos#14]
Intel chip/OS 13:
the app gets added to background apps, but upon restart it does not launch.

Apple Silicon/OS 14:
Item shows up in "Allow in the Background" as expected, but when unchecking "Launch at Login" it isn't toggled off as expected. This behavior works on Intel/OS 13. Tests on Intel 12 and 14 incoming.

**Comment by taramk** [comment]
just tested on OS 12 - it does launch at login as expected, though i couldn't find where it exists in settings since it's different than 13 (nothing is listed in login items)

**Comment by ericmaciel** [comment]
In macOS 12 the login items are in "Users & Groups", but using this method the app doesn't appear in that list. As far as I know, the status is only visible from the app.

**Comment by taramk** [comment]
@ericmaciel - i have another request as part of this - can you somehow differentiate between legacy and modern in the menus? maybe a label that says Legacy or Modern? sometimes i'm testing them together and it'd be helpful to know which is which.

**Comment by taramk** [comment]
@ericmaciel - i should clarify with you on Legacy vs. Modern - what compatibility do we expect? 

* Modern: requires 13.0+
* Legacy: Works on 12, should it work on 13 and 14 or no?

**Comment by ericmaciel** [comment]
@taramk 
- Modern: correct, 13.0+
- Legacy: requires 10.6+, and should work on 12, 13 and 14 as well.

**Comment by taramk** [comment]
@ericmaciel - I do see that Legacy works on 14 now, I just have a couple questions:

1. I'm seeing the below extra background apps on OS 14, is that normal/expected?
![image](https://github.com/darwinkitdev/upwork-demos/assets/1813419/8555e510-316a-4e1a-9a62-0c7f661ac443)

2. On OS 13 and 14, the "Allow in the Background" apps aren't toggled off when I uncheck "Launch at Login" in LaunchAtLogin-Legacy's menu. The app doesn't launch on restart though (as expected) so is it intentional that they stay toggled on in "Allow in the Background" even if the app doesn't launch on startup?

**Comment by ericmaciel** [comment]
@taramk 

1. These extra items are actually leftovers from the OS update. The binaries that these items would open don't even exist. It seems to be a bug in the OS update process.
2. Yes, it's kind of a bug in the OS too. The items under "Allow in the Background" only indicate that the app or helper/launcher can run in the background. However, there is also a flag that indicates that the app is in "Login Items", but it doesn't appear in the list using this method. What is displayed in the LaunchAtLogin-Legacy app menu is this flag.
