### ISSUE TITLE
SnapResize: doesn't use entire space/placement shifted down?

### ISSUE THREAD

**Issue by taramk** [darwinkitdev/upwork-demos#16]
Gif attached. On a 12" Macbook Air/Intel/OS 13, the apps aren't quite placed where they should be vertically. if you look at the left/right/top ones, there's a good chunk of empty space above them. and on the bottom ones, they go below/behind the dock.

![2023-11-14 15 22 55](https://github.com/darwinkitdev/upwork-demos/assets/1813419/9f85048f-8c6a-42a1-b9f8-40258fe344a4)

**Comment by ericmaciel** [comment]
@taramk It's fixed, but I've noticed another possible issue. The centering option is actually filling the entire screen. Is this the desired behavior or is it just to center the window while maintaining its current size?

**Comment by taramk** [comment]
@ericmaciel - you're right - it should just center it and maintain its current size.
