### ISSUE TITLE
HexPicker: cursor frozen on OS 12

### ISSUE THREAD

**Issue by taramk** [darwinkitdev/upwork-demos#17]
On OS 12, when I build and run HexPicker, the cursor turns into the picker as expected but it's frozen in place. This is true whether I use the keyboard shortcut or choose Pick Color from the menu. If I click in place it does save the color, but I cannot move the cursor. (I'm able to access other windows/free the cursor by using the trackpad gesture to show all windows, but the frozen picker remains on screen.)

This is not happening on OS 13 or 14.

**Comment by taramk** [comment]
@ericmaciel let me know if you need any more info on this one

**Comment by ericmaciel** [comment]
Ok, I'll take a look and let you know.

**Comment by ericmaciel** [comment]
@taramk I managed to fix it.

**Comment by taramk** [comment]
looks good, thanks!
