### ISSUE TITLE
MenuShot bugs

### ISSUE THREAD

**Issue by taramk** [darwinkitdev/upwork-demos#7]
1. "Capture screen" always produces a screenshot of an empty desktop, no windows
2. Screenshotting a specific window doesn't produce a screenshot (nothing happens when window is selected)
3. App asks for permissions on startup even if permission has previously been granted

Things to know:
* I'm running Sonoma 14.0
* I commented out the lines in the makefile related to signing (screenshot below)

Video showing all 3 issues:
https://www.loom.com/share/aa4ae41304c246b3a5ac17e79acfbbba?sid=cae658ff-cb94-42fd-b861-c7ae53a616c5

Screenshot of code commented out:
<img width="808" alt="image" src="https://github.com/darwinkitdev/upwork-demos/assets/1813419/2667934a-4f12-4385-bfb8-08af2f87780c">

**Comment by ericmaciel** [comment]
I tried to reproduce it exactly as you described. If I comment out the lines in the makefile related to signing, the app really can't take screenshots of a window and the full screen screenshots only take the background image. But if I don't comment out those lines and the app is signed, everything works as expected. So I think this step is really essential.

To sign the app you need a developer ID and a development certificate installed. You can get the certificate via Xcode or Apple's developer portal. If necessary, I can try to describe a more detailed step-by-step description of how to do this.

To find out if you already have a certificate installed, you can check Keychains. Go to the My Certificates tab and look for a certificate that contains something like "Apple Development: <developer_name>".

**Comment by taramk** [comment]
Thank you for looking into it, Eric! Very interesting that signing affects functionality this way. I'll chat w/ Jeff when he gets back this week and we may have further questions for you.
